"""SQLite 저장 계층의 공개 인터페이스를 제공합니다."""

from .chats import (
    Chat,
    ChatError,
    create_additional_chat,
    delete_chat,
    get_chat,
    get_default_chat,
    get_or_create_default_chat,
    list_chats,
)
from .connection import DatabaseError, connect_database, database_path_from_url
from .initial_assessments import (
    INITIAL_ASSESSMENT_ANSWER_COUNT,
    InitialAssessmentError,
    can_complete_initial_assessment,
    finish_initial_assessment,
    is_initial_assessment_active,
    require_initial_assessment_completion,
    start_initial_assessment,
)
from .learning_profiles import (
    LearningProfile,
    LearningProfileError,
    LevelChange,
    ProficiencyTest,
    add_level_change,
    add_proficiency_test,
    change_learning_level,
    get_learning_profile,
    list_level_changes,
    list_proficiency_tests,
    save_learning_profile,
)
from .messages import Message, MessageError, add_message, list_messages
from .review_words import (
    ReviewWord,
    ReviewWordError,
    delete_review_word,
    list_review_words,
    save_review_word,
)
from .schema import initialize_database
from .study_records import (
    StudyRecord,
    StudyRecordError,
    add_study_record,
    list_recent_study_records,
    upsert_study_record,
)

__all__ = [
    "INITIAL_ASSESSMENT_ANSWER_COUNT",
    "Chat",
    "ChatError",
    "DatabaseError",
    "InitialAssessmentError",
    "LearningProfile",
    "LearningProfileError",
    "LevelChange",
    "Message",
    "MessageError",
    "ProficiencyTest",
    "ReviewWord",
    "ReviewWordError",
    "StudyRecord",
    "StudyRecordError",
    "add_level_change",
    "add_message",
    "add_proficiency_test",
    "change_learning_level",
    "add_study_record",
    "can_complete_initial_assessment",
    "connect_database",
    "create_additional_chat",
    "database_path_from_url",
    "delete_chat",
    "delete_review_word",
    "finish_initial_assessment",
    "get_chat",
    "get_default_chat",
    "get_learning_profile",
    "get_or_create_default_chat",
    "initialize_database",
    "is_initial_assessment_active",
    "list_chats",
    "list_level_changes",
    "list_messages",
    "list_proficiency_tests",
    "list_recent_study_records",
    "list_review_words",
    "require_initial_assessment_completion",
    "save_learning_profile",
    "save_review_word",
    "start_initial_assessment",
    "upsert_study_record",
]
